### ISSUE TITLE
怎么在vue3中使用vue2中的$on

### ISSUE THREAD

**Issue by Polaris-z** [vuejs/rfcs#102]
怎么在vue3中使用vue2中的$on？

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Vue 3 isn't released yet, not all features have been implemented
