### ISSUE TITLE
"Rendered" links from pull requests need updating

### ISSUE THREAD

**Issue by ky-is** [vuejs/rfcs#108]
The [vue-next changelog](https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md) links to https://github.com/vuejs/rfcs/pulls?q=is%3Apr+is%3Amerged+label%3A3.x, but all of the "Rendered" links are broken in the PRs now due to file renaming. We should probably edit the original posts so that it is easy to reference the RFCs that have landed. Here are the links that currently need updating:

https://github.com/vuejs/rfcs/pull/8: https://github.com/vuejs/rfcs/blob/master/active-rfcs/0005-replace-v-bind-sync-with-v-model-argument.md

https://github.com/vuejs/rfcs/pull/20: https://github.com/vuejs/rfcs/blob/slots-unification/active-rfcs/0006-slots-unification.md

https://github.com/vuejs/rfcs/pull/27: https://github.com/vuejs/rfcs/blob/functional-async-api-change/active-rfcs/0007-functional-async-api-change.md

https://github.com/vuejs/rfcs/pull/28: https://github.com/vuejs/rfcs/blob/render-fn-api-change/active-rfcs/0008-render-function-api-change.md

https://github.com/vuejs/rfcs/pull/29: https://github.com/vuejs/rfcs/blob/global-api-change/active-rfcs/0009-global-api-change.md

https://github.com/vuejs/rfcs/pull/31: https://github.com/vuejs/rfcs/blob/master/active-rfcs/0011-v-model-api-change.md

https://github.com/vuejs/rfcs/pull/32: https://github.com/vuejs/rfcs/blob/master/active-rfcs/0012-custom-directive-api-change.md
https://github.com/vuejs/rfcs/pull/95: https://github.com/vuejs/rfcs/blob/master/active-rfcs/0014-drop-keycode-support.md

https://github.com/vuejs/rfcs/pull/97: https://github.com/vuejs/rfcs/blob/master/active-rfcs/0015-remove-filters.md

https://github.com/vuejs/rfcs/pull/98: https://github.com/vuejs/rfcs/blob/master/active-rfcs/0016-remove-inline-templates.md

Hoping someone with permissions can do this. Thank you!

**Comment by yyx990803** [comment]
Thanks! Updated.
