### ISSUE TITLE
Discuss the best practices of project structure

### ISSUE THREAD

**Issue by cawa-93** [vuejs/rfcs#115]
In this discussion, I would like to raise in the community questions about best practices for organizing project structure.

Vue is beautiful not least in that it allows you to organize the project structure as you want. However, I would like to hear the views of the community on this topic. I would like people who have experience working on major projects to share their experiences and thoughts on the subject.

In Vue 2, we have several global entities: components, mixins, plugins, etc.

Components may be:
* Independent (such as the `Button` component). Which can be used wherever.
* Depend on others. For example, the `Slide` component, which can only be in the `Slider` component. 
* Some components are and depend on routes.

For me, it causes some confusion. And I have some questions to discuss:
* How to name components and component files to distinguish independent components from those that are dependent on other components or dependent on the routes.
* How to organize directory structure? Is it necessary to embed dependent components into one another? Is it worth keeping a flat structure? Is it necessary to separate components for routes into a separate directory? 

In Vue 3 With the advent of composition api, another entity emerges - composition functions. 
* How should such functions be named so that they can easily be distinguished from normal functions?
* Should I somehow separate the composite functions I wrote from those installed through npm?
* How to organize directory structure?

**Comment by posva** [comment]
Except for the Composition API, here are some well adopted guidelines: https://github.com/chrisvfritz/vue-enterprise-boilerplate
Regarding component naming, we have style guidelines https://vuejs.org/v2/style-guide/

Composition functions are often named with the prefix `use`, there isn't a standard yet regarding the folder but naming it `use` is a possibility:

```js
import useMouse from '@/use/mouse'
```
