### ISSUE TITLE
Create more than one active RFC

### ISSUE THREAD

**Issue by Aferz** [vuejs/rfcs#13]
Hello.

I wanna create another RFC for an idea that I had for Vue 2.6 but I've found that I can't without breaking the rules of README file.

The problem is I already have one `0000-template.md` file.

I just wanna ask what should I do. Should I wait until my last RFC is resolved? Or can I create, for example, a `0000-template-1.md` file?

Thanks.

**Comment by yyx990803** [comment]
I'm not sure if I get your problem... you can create different branches in your fork. And your proposals will have different names anyway.

**Comment by Aferz** [comment]
Oh my... you are right sorry. I don't know what I was thinking.

Thanks.
