### ISSUE TITLE
Custom async props validation

### ISSUE THREAD

**Issue by filipsobol** [vuejs/rfcs#147]
Hi,

With `Suspense` introduced in Vue 3, is it possible to add support for custom async [props validation](https://vuejs.org/v2/guide/components-props.html#Prop-Validation)?

One example use case is similar to the one from [Vuelidate documentation](https://vuelidate.js.org/#sub-asynchronous-validation):

```javascript
props: {
    propA: {
        validator: async (value) => {
            const response = await fetch(`/api/unique/${value}`);
            return Boolean(await response.json());
        }
    }
}
```

Another one would be [validate](https://logaretm.github.io/vee-validate/advanced/programmatic-validation.html#the-validate-function) method from `vee-validate` library, which returns a Promise.

**Comment by yyx990803** [comment]
Anything async is inherently complex implementation-wise and it would be best to isolate it in `async setup` for all possible cases. I don't see enough benefit to justify async validators when this can be done in userland.
