### ISSUE TITLE
Some RFC already implemented in the latest Vue, should it be classified?

### ISSUE THREAD

**Issue by chenxeed** [vuejs/rfcs#162]
Hi!

I'm currently reading the RFC in the `./active-rfcs` folder, and I realized some RFC were already implemented in the production of the latest release, for ex:

https://github.com/vuejs/rfcs/blob/master/active-rfcs/0001-new-slot-syntax.md
https://github.com/vuejs/rfcs/blob/master/active-rfcs/0002-slot-syntax-shorthand.md
https://github.com/vuejs/rfcs/blob/master/active-rfcs/0003-dynamic-directive-arguments.md

Currently they have been implemented and released in Vue `v2.6.x`.

Since there's a [RFC Lifecycle](https://github.com/vuejs/rfcs#the-rfc-life-cycle) statuses, should we classify the current list in `./active-rfcs` to simply define which one that has been landed, or rejected?

**Comment by smolinari** [comment]
Yeah, unfortunately, in the two slot RFCs, the links back to the PRs are missing. It's the PR that shows the status. i.e. merged means it's been adopted.  

https://github.com/vuejs/rfcs/pull/2
https://github.com/vuejs/rfcs/pull/3
https://github.com/vuejs/vue/pull/9373

You'd probably be better off looking at the PRs, as they link to the "rendered" detailed descriptions, which you are reading. The merged and closed PRs have been adopted, i.e. they are or will be added to Vue. 

(that is my understanding of how the RFC process works)

Scott

**Comment by posva** [comment]
I fixed the dead links in the Prs mentioned on the issue. Feel free to leave a comment when a _Rendered_ link is dead
