### ISSUE TITLE
beforeRouteUpdate => onBeforeRouteUpdate?

### ISSUE THREAD

**Issue by gregveres** [vuejs/rfcs#164]
Should there be a router life cycle hook that can be called inside setup that is the equivalent of beforeRouteUpdate? 

I have just run into a situation where I need the view model of the component to get updated when the parameters of the route change. But the view model only exists within setup.  

my view model is a typescript class that contains all the logic of the component. 

I am left with these choices:

- create a new function that gets returned from setup that calls the method on my vm class
- return the entire vm class instance from setup so I can cast the component to be able to call the vm's method
- look at using onBeforeUpdate and determine if the component is being updated due to a route change. 

Or, if there was an onBeforeRouteUpdate() that I could call from within setup, all of this would be trivial and intuitive.

**Comment by posva** [comment]
The function exists on vue router 4. It has to be built as a plugin for vue router 3
