### ISSUE TITLE
since we treat all `onSomething` as `v-on`, how to pass handler as props?

### ISSUE THREAD

**Issue by Jokcy** [vuejs/rfcs#174]
as rfs 008, we will treat all `onSomething` as `v-on`, which means it will bind to the root element of this component.

what if I has a component like this:
```
<div>
  <input />
</div>
```

and I want to accept a props like `onInput` which should bind on the `input` element.

is that means I need to call the handler like `whenInput`? any way to skip the default behavior?

**Comment by yyx990803** [comment]
Just declare it as a prop and it will no longer bind to the element as a native listener.

**Comment by Jokcy** [comment]
@yyx990803 But how about functional components? It's easy now just using a function not define a functional component. But if I have this issue, I still need to turn the functional component back to instance component.

**Comment by Jokcy** [comment]
@yyx990803 And also if I have a component like `MyInput` which just wrapper a normal `input`, and I listen to the `input` event and do some data handle. Also I accept a `onChange` props to tell user when the data change, in this case, not every input will cause `onChange`.

Then the user may use `onInput` in my componnet, and it will also work (not currectlly) which not my expect. It will be very confusing

**Comment by yyx990803** [comment]
You *can* declare props for functional components.

And for your component - it is your responsibility to provide a consistent interface. The current API doesn’t prevent you from doing that.

**Comment by Jokcy** [comment]
@yyx990803 But it do cripple the ability of functional component. 

As I expect, the functional component is very good for implement *High Order Component*. The HOC handle some of the `WrapperedComponent's` props, and pass other props down directly.

But with the default behavior, we need to declare all `onSometing` props which `WrapperedComponent` needs in the HOC. It makes declare HOC inconvenient and it make HOC not that **Higher** if HOC should care props that it not handled
