### ISSUE TITLE
Add $calls to avoid boilerplate methods when calling built DOM methods?

### ISSUE THREAD

**Issue by lee-chase** [vuejs/rfcs#186]
Perhaps I missed spotting a good way to do this, but I currently find myself revisiting components such as the following to add methods like focus, blur, stepUp, stepDown to call internal DOM mehtods.

Appologies for Vue2 syntax.

```html
<template>
  <div class="my-form-item>
    <label>{{label}}
       <input :id="id" ref="input" />
    </label>
  </div>
</template>

<script>
.
.
.
    methods: {
        focus() {
            this.$refs.input.focus();
        }
   }    
.
.
.
</script>
```

As a convenience, it would be nice to skip the method definition and pass methods to where they are needed. 

Suggested template syntax

```html
<template>
  <div class="my-form-item>
    <label>{{label}}
       <input :id="id" ref="input" v-call="$calls" />
    </label>
  </div>
</template>
```

It would make sense for $calls (or a better name) to behave in a similar way in terms of falling through to $attrs and $listeners seen in https://github.com/vuejs/rfcs/blob/49de6decac4dc99840410d082e3bd7c98b580193/active-rfcs/0031-attr-fallthrough.md

**Comment by posva** [comment]
I don't think this extra api needs to be in core since it can be added as a mixin in Vue 2 and a `useMethods` (or any other name) in Vue 3 to generate all the necessary methods given a `$refs` name

**Comment by lee-chase** [comment]
> I don't think this extra api needs to be in core since it can be added as a mixin in Vue 2 and a `useMethods` (or any other name) in Vue 3 to generate all the necessary methods given a `$refs` name

You may be right, I suspect the ask is for impossible magic to enable a component to have no knowledge of the methods being called in a natural way e.g. `component.blur()`. Passing the method name as a string makes that possible but does not feel right e.g. `component.callsMethod('blur', args)`.

In Vue2 I've ended up with this mixin, which requires components using it to define which can be called and the target of the method.

```js
const methodsMixin = methodDefs => {
  const methods = {};
  for (let methodDef of methodDefs) {
    methods[methodDef.name] = function(...args) {
      this.$refs[methodDef.ref][methodDef.name](...args);
    };
  }

  return {
    methods: methods,
  };
};

export default methodsMixin;
```

**Comment by lee-chase** [comment]
Will close, while I still think it would be nice to avoid the boilerplate in some way I have not come up with a good solution.
