### ISSUE TITLE
Vue 3 is now in RC!

### ISSUE THREAD

**Issue by yyx990803** [vuejs/rfcs#189]
# Vue 3 is now in RC!

We are very excited to announce that Vue 3.0 has entered RC (Release Candidate) stage!

Entering the RC stage means that both the API and implementation of Vue 3 core have stabilized. In principle, we do not expect to introduce new major features or breaking changes before the final release. Most official framework parts also now have v3 support. Please check [here](https://github.com/vuejs/vue-next#status-of-the-rest-of-the-framework) for the latest status.

## New Documentation

The Vue docs team have been updating our docs for v3 and it is now available at [v3.vuejs.org](https://v3.vuejs.org/)! It has been a massive undertaking and many thanks to the hard work by the docs team: @NataliaTepluhina, @bencodezen, @phanan and @sdras. The new docs has been meticulously migrated to cover differences between v2 and v3, runs on VuePress, and has improved code samples that can be edited inline.

For a quick overview on what's new and what's changed, please refer to the [Migration Guide](https://v3.vuejs.org/guide/migration/introduction.html).

Please note that the new documentation, especially the Migration Guide, is still a work in progress, and we will continue to polish it throughout the RC stage.

## Initial DevTools Support for v3

We have also published a [beta version of the new Vue Devtools with initial v3 support](https://github.com/vuejs/vue-devtools/releases/tag/v6.0.0-beta.1), thanks to the amazing work by @Akryum.

The devtool has received a major refactor to better decouple its core logic from different supported Vue versions. The interface also has a new look implemented with Tailwind CSS. Currently, only component inspection is supported - but more features will be coming soon.

~~At the moment, the beta channel of Vue Devtools is still under review in the Chrome Web Store, but you can download and install the extension locally by following the instructions in the link above.~~

**Update**: Devtools beta has been approved and now [available on the Chrome Web Store](https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg) (Note: the devtools requires `vue@^3.0.0-rc.1`)

## Trying It Out

If you are interested in trying out Vue 3 today, there are a few ways to do it:

- Play with it on [Codepen](https://codepen.io/team/Vue/pen/KKpRVpx)

- Start a project using [Vite](https://github.com/vitejs/vite) with:

  ```
  npm init vite-app hello-vue3
  ```

  Vite comes with [`<script setup>`](https://github.com/vuejs/rfcs/blob/sfc-improvements/active-rfcs/0000-sfc-script-setup.md) and [`<style vars>`](https://github.com/vuejs/rfcs/blob/sfc-improvements/active-rfcs/0000-sfc-style-variables.md) support in Single File Components.

- We are have a pending PR on [first-class v3 support in vue-cli](https://github.com/vuejs/vue-cli/pull/5637) - which will be available soon.

## Future Work

We haven't been able to complete full IE11 support for the RC, so we will continue to work on that.

At the same time, our primary focus will shift to documentation, migration, and compatibility. Our current goal is to provide clear documentation for starting new projects with v3, and help library authors upgrade their packages to support v3. The docs team will continue to polish the migration guide and v3 documentation based on feedback from the community.

Migrating non-trivial applications from v2 to v3 will likely be a much slower process.  We will provide code mods and tools to help with such migrations, but in most cases, this will depend on how fast the project's dependencies can be upgraded to support Vue 3. It is also important to evaluate whether the risk and time investment of upgrading is worth it - since Vue 2 will continue to be supported. We plan to dedicate a focus period after 3.0 release to back-port features into v2 via compatibility plugins. We are already seeing success with this approach in [@vue/composition-api](https://github.com/vuejs/composition-api).

### Experimental Features

There are a few features that are shipped in the RC release, but have been marked experimental:

- `<Suspense>`
- [`<script setup>`](https://github.com/vuejs/rfcs/blob/sfc-improvements/active-rfcs/0000-sfc-script-setup.md)
- [`<style vars>`](https://github.com/vuejs/rfcs/blob/sfc-improvements/active-rfcs/0000-sfc-style-variables.md)

These features are shipped now in order to collect feedback from actual usage, but they may still receive breaking changes / major adjustments. They will likely remain experimental in 3.0, and become finalized as part of 3.1.

**Comment by CyberAP** [comment]
A truly great work by the whole Vue.js community! I've never been so excited about a software major release, glad to see the final release approaching closer and closer!

**Comment by yyx990803** [comment]
@CyberAP thank you, it wouldn't have been possible without input and contribution from community members like you!

**Comment by altitudems** [comment]
Amazing work by all! You should be proud!

**Comment by wa3l** [comment]
@yyx990803 congrats! Love the script setup feature, such a small thing but the boilerplate and extra two levels of indentation were probably gonna get old really fast. Nice work 👌

**Comment by nasserff** [comment]
@yyx990803 Congrats! What a great accomplishment 🎉🎉🎉🎉

**Comment by ahsandev2019** [comment]
Congratss

**Comment by johnnywang1994** [comment]
It’s very lucky for me to have Vuejs as my first framework, not only because it saves my time, but also teaches me a lot, Congrattss!!

**Comment by cdll** [comment]
hooray！

**Comment by nanyang24** [comment]
CongrattSSSSSS

**Comment by rumblefrog** [comment]
Thanks for marking the still-experimental features!

**Comment by xiaohp** [comment]
Congrats!

**Comment by BillyChannn** [comment]
Congrats! Amazing work!

**Comment by wanmaoor** [comment]
Great job!

**Comment by peizhongli** [comment]
Congrats!

**Comment by zy0228** [comment]
good job!

**Comment by ycmjason** [comment]
yay

**Comment by annder** [comment]
nice!

**Comment by bapex** [comment]
Congrats!!!

**Comment by agileago** [comment]
Amazing work 🐂 🐂 🐂 🐂 🐂 🐂 🐂 🐂 🐂 🚀🚀🚀🚀🚀🚀🚀🚀

**Comment by FedericoBiccheddu** [comment]
Thank you so much for the hard work.

**Comment by liumuu** [comment]
🐮🍺

**Comment by shengxinjing** [comment]
Congrats！

**Comment by Otto-J** [comment]
good job!

**Comment by assoft** [comment]
Congrats!!!

**Comment by yaodebian** [comment]
Thank you for your efforts so far. Congrats!!!

**Comment by usernane** [comment]
Congratulations. Thanks for all people who work on making Vuetify better.

**Comment by lovelyBug** [comment]
Congrats！

**Comment by jacekkarczmarczyk** [comment]
> Thanks for all people who work on making Vuetify better.

@usernane And Vue as well :)

**Comment by xyantelope** [comment]
Congrats!!!

**Comment by Rain120** [comment]
Amazing 🐮🍺🐮🍺🐮🍺

**Comment by Franslee** [comment]
great

**Comment by xiaoboost** [comment]
🐮🍺🐮🍺🐮🍺

**Comment by liupangus** [comment]
great!

**Comment by wenzi0github** [comment]
newbee

**Comment by ChpShy** [comment]
Congrats！

**Comment by Yanggoing** [comment]
🚀🚀🚀Congrats!

**Comment by SigureMo** [comment]
Congrats ♪⸜(๑ ॑꒳ ॑๑)⸝♪✰

**Comment by JoeyQiuYang** [comment]
期待啊

**Comment by fireairforce** [comment]
gogogo!

**Comment by mingyuyuyu** [comment]
牛逼

**Comment by vinayakkulkarni** [comment]
Can't wait to replace [composition api](https://github.com/vinayakkulkarni/janak/blob/main/template/base/_package.json#L34) with "vue" :)

**Comment by eshimischi** [comment]
Congratulations, guys, soon we gonna get a really awesome tool to build our projects! Hip Hip!

**Comment by arswaw** [comment]
It is so exciting to see the Vue project team embrace ES6 modules like they have. I think that the ability to write data-driven web UIs without having to use Node or rely on NPM will be a significant and positive change in the industry.

**Comment by hzyhbk** [comment]
🐮🍺🐮🍺🐮🍺

**Comment by neverlous** [comment]
cool，i will try

**Comment by neverlous** [comment]
下周赶紧试试

**Comment by loveyunk** [comment]
amazing!!!

**Comment by xieyezi** [comment]
Amazing!

**Comment by songxx1989** [comment]
抓紧学习

**Comment by klren0312** [comment]
Congratulations

**Comment by onaug6th** [comment]
Congrats！

**Comment by isArtJay** [comment]
厉害了

**Comment by tuantmtb** [comment]
Congrats!

**Comment by Randysheng** [comment]
cool

**Comment by ZhangDubhe** [comment]
wow！

**Comment by RayDarar** [comment]
Congrats! :smile:

**Comment by brolnickij** [comment]
<3

**Comment by notbucai** [comment]
go

**Comment by parthibd** [comment]
Congrats guys! Can't wait for GA of Vue 3 :) :)

**Comment by ghtao666** [comment]
期待

**Comment by enentyour** [comment]
Congrats !!!

**Comment by WaldemarEnns** [comment]
dang, finally! 💯 👍 🎉

**Comment by xinbeimousha** [comment]
amazing!!!!!!

**Comment by stephenjason89** [comment]
Thank you for the great work!

**Comment by AlexandreBonaventure** [comment]
well done !

**Comment by Xochi** [comment]
Awesome!

**Comment by shaonialife** [comment]
期待

**Comment by chalermporn** [comment]
Congrats ^^

**Comment by foxxyz** [comment]
Fantastic news and awesome work. Here's to a bright future for Vue 3 🥂 !

**Comment by mikoyats** [comment]
Congratulations! Can't wait 👀

**Comment by Linkontoask** [comment]
Waiting for the first stable release

**Comment by Equinox07** [comment]
Watching VueConf over and over again... Practicing through rfcs to this stage.... Man i couldn't be any happier. Lets make a Toast 🥂. Congrats once again to the Glory of Vue. 🥂 🚀🚀🚀🚀🚀🚀🚀🚀

**Comment by maybeyourking** [comment]
Wow cool!

**Comment by muzig** [comment]
so exciting!💪

**Comment by Bruslaan** [comment]
Somebody an idea how to disable the error warning of Vetur "The template root requires exactly one element.eslint-plugin-vue".

**Comment by StanleyMasinde** [comment]
I'm so excited about this version and hope to contribute more

**Comment by StanleyMasinde** [comment]
> Somebody an idea how to disable the error warning of Vetur "The template root requires exactly one element.eslint-plugin-vue".

I think it is because Vetur is configured for Vue 2.x

**Comment by daniele-orlando** [comment]
Awesome! Love you so much guys for the immense effort in making Vue better day after day. ❤️

**Comment by youchaojun** [comment]
就没有一个中文评论么，我来打个样，坐等文档中

**Comment by WeidanLi** [comment]
### six six six,

**Comment by Kurira** [comment]
Will `script setup` work with webpack on initial release?

**Comment by Remote-version-git** [comment]
That's very great.

**Comment by yohannlegrand** [comment]
So good !

**Comment by alekseiOdegovC** [comment]
GJ !!

**Comment by mes113** [comment]
GJ!!!

**Comment by flowers20190510** [comment]
great

**Comment by mrwdhasd0903** [comment]
is so niubility

**Comment by rizoadev** [comment]
Congrats!!!

**Comment by 1066826101** [comment]
支持支持

**Comment by Rajdeepc** [comment]
Great news!!

**Comment by HaxorNoob** [comment]
Congrats ( :

**Comment by GokulKrishnanstartupverge** [comment]
Hi So, I planned to choose vuejs for my company as the company grows. I will Try to contribute from our end as the company grows. Looking for more awesome features from vuejs community. Tc Folks

**Comment by yooyea** [comment]
大哥！求IE11！嘤嘤嘤！

**Comment by 3529** [comment]
棒棒的

**Comment by ryanelian** [comment]
Does vue-loader 16 supports Vue 2?

**Comment by Line999** [comment]
并没有发现vue 3.0的文档所在

**Comment by Picknight** [comment]
> 并没有发现vue 3.0的文档所在

https://v3.vuejs.org/

**Comment by mrnicai** [comment]
有3.0文档嘛，没看到

**Comment by wzt-procedure** [comment]
> 有3.0文档嘛，没看到

https://v3.vuejs.org/

**Comment by KirkZheng** [comment]
表示一脸懵逼

**Comment by brgrz** [comment]
This [article](https://madewithvuejs.com/blog/vue-3-roundup) says 

> As Evan You summarized it, Vue 3 is faster, smaller, more maintainable and it's easier to target native.

What can we expect regarding the native "story" of Vue 3? What exactly does "easier to target native" mean? 

Thank you

@yyx990803

**Comment by leopiccionia** [comment]
@brgrz Vue 3.0 decoupled much of the core compilation and rendering logic from the DOM, so it's much easier to replace the default DOM-based compiler and runtime by custom implementations.

Examples of WIP custom renderers targetting native platforms include [`nativescript-vue-next`](https://github.com/rigor789/nativescript-vue-next) and [`vue-nodegui`](https://vue.nodegui.org/).

**Comment by ErickLuis00** [comment]
I really liked <script setup> it makes the components much cleaner and simpler

**Comment by radiorz** [comment]
加油！！！

**Comment by xstxhjh** [comment]
Well done!

**Comment by Lrunlin** [comment]
> 大哥！求IE11！嘤嘤嘤！

正经人谁用IE呀

**Comment by johnwc** [comment]
What is the ETA of a full release?

**Comment by leopiccionia** [comment]
Vue 3 was officially released in September last year.

It's not yet the default version in NPM and docs, though. According to Evan's [recent presentation](https://docs.google.com/presentation/d/1Lu1X6dyofyWqE6lpWsdUAkHMWm9pB6A9bs187iIUin4/mobilepresent?slide=id.gd20ff24a73_0_177) in VueConf.US, it's expected to happen by the end of the semester.
