### ISSUE TITLE
If I use "<script setup>", how can I "export" the "toRefs(state)"？

### ISSUE THREAD

**Issue by et3323668** [vuejs/rfcs#250]
```
<template>
  <!-- I don't want to use 'state.value', so I use 'toRefs' -->
  <div>{{label}}: {{value}}</div>
</template>

<script>
import { reactive, ref, toRefs } from 'vue'
export default {
  setup(){
    const label = ref('hello')
    const state = reactive({
       value: 0
    }) // If the object has more attribute values
    return {
      ...toRefs(state),
      label
    }
  }
}
</script>
```

If I use "<script setup>"
```
<script setup>
  import { reactive, toRefs } from 'vue'
  export const label = ref('hello')
  // todo: How can I export toRefs(state)
</script>
```
How can I "export" the "toRefs(state)"？

**Comment by LinusBorg** [comment]
Please use chat.vuejs.org to ask for help.

**Comment by DannyFeliz** [comment]
@LinusBorg I have the same doubt, how can we export state using toRefs?

**Comment by ringeringeraja** [comment]
@DannyFeliz have you managed to find a solution already?

**Comment by ubbcou** [comment]
[explicit expression, I think](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmltcG9ydCB7IHJlZiwgcmVhY3RpdmUsIHRvUmVmcywgZGVmaW5lQ29tcG9uZW50IH0gZnJvbSAndnVlJ1xuXG4gIC8qXG4gIGV4cG9ydCBkZWZhdWx0IGRlZmluZUNvbXBvbmVudCh7XG4gICAgc2V0dXAoKSB7XG4gICAgICBjb25zdCBzdGF0ZSA9IHJlYWN0aXZlKHtcbiAgICAgICAgbXNnOiAnaGVsbG8nLFxuICAgICAgICBuYW1lOiAnbnVvbmFtdSdcbiAgICAgIH0pXG4gICAgICByZXR1cm4ge1xuICAgICAgICAuLi50b1JlZnMoc3RhdGUpLFxuICAgICAgfVxuICAgIH1cbiAgfSlcbiAgKi9cbjwvc2NyaXB0PlxuXG48c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVmLCByZWFjdGl2ZSwgdG9SZWZzLCBkZWZpbmVDb21wb25lbnQgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHN0YXRlID0gcmVhY3RpdmUoe1xuICBtc2c6ICdoZWxsbycsXG4gIG5hbWU6ICdudW9uYW11J1xufSlcbi8vIGV4cGxpY2l0IGV4cHJlc3Npb25cbmNvbnN0IHsgbXNnLCBuYW1lIH0gPSB0b1JlZnMoc3RhdGUpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19IHt7IG5hbWUgfX08L2gxPlxuICA8aW5wdXQgdi1tb2RlbD1cIm1zZ1wiPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59In0=)
