### ISSUE TITLE
how to use await in tag <script setup>

### ISSUE THREAD

**Issue by syifeng** [vuejs/rfcs#266]
```javascript
<script setup async>
import { ref, watch } from 'vue'
import HelloWorld from './components/HelloWorld.vue'
import { getMedInfos } from './api/medInfo'
const msg = ref('msg')
export const medInfos = await getMedInfos(1, 10)
</script>
```
when I use the await function in the tag '<script setup>' I got the error
<script setup> cannot contain ES module exports
what should i do
thanks for the answer

**Comment by CyanSalt** [comment]
I think the `setup()` method should be synchronous. Maybe you need to use `watchEffect` to wrap asynchronous processes.

**Comment by aykxt** [comment]
```diff
- export const medInfos = await getMedInfos(1, 10)
+ const medInfos = await getMedInfos(1, 10)
```
You should not export variables as they are already available by default in script setup.
> Any top-level bindings (both variables and imports) declared inside <script setup> are directly exposed to the template render context [Read more](https://github.com/vuejs/rfcs/blob/script-setup-2/active-rfcs/0000-script-setup.md#top-level-bindings-are-exposed-to-template)

**Comment by Shyam-Chen** [comment]
Top level `await`: https://github.com/vuejs/rfcs/blob/script-setup-2/active-rfcs/0000-script-setup.md#top-level-await

**Comment by yyx990803** [comment]
It "just works". But make sure to call all lifecycle and `watch` methods before the first `await` since those rely on the presence of the current active instance (we have been discussing how to detect and guard against this via tooling)

**Comment by TuiMao233** [comment]
Include the current component through the asynchronous component
