### ISSUE TITLE
<script setup>语法糖bug

### ISSUE THREAD

**Issue by gouqie722** [vuejs/rfcs#274]
使用<script setup>编写的组件，打包后的项目无法加载此组件

**Comment by antfu** [comment]
Please provide more context and proper repro if you believe it's a bug. Otherwise, please use Discord or Stackoverflow to ask questions.

**Comment by gouqie722** [comment]
You can find a demo and try it

**Comment by gouqie722** [comment]
> 如果您认为这是一个错误，请提供更多背景信息并进行适当的复制。否则，请使用Discord或Stackoverflow提出问题。

You can find a demo and try it

**Comment by DevilLeven** [comment]
@gouqie722 您的问题解决了吗 ，我也遇到同样问题，打包结果不会包含dom。
![image](https://user-images.githubusercontent.com/21081386/114644746-ae092200-9d0a-11eb-9379-6c36eac8ad50.png)
