### ISSUE TITLE
vue.js devtool can not detecte anything when i use vitejs

### ISSUE THREAD

**Issue by kvsur** [vuejs/rfcs#275]
vue.js devtool can not detecte anything when i use vitejs

**Comment by kvsur** [comment]
when I try reinstall devtool but still not work

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
