### ISSUE TITLE
<script setup> can not export any variable

### ISSUE THREAD

**Issue by buqiyuan** [vuejs/rfcs#280]
![image](https://user-images.githubusercontent.com/39730999/110512899-9d302400-8140-11eb-931c-3e9b1e51d821.png)
I can not export any variable! What did I do wrong？
you can try to run the [repo](https://github.com/buqiyuan/vue-rfcs/blob/main/src/views/index/index.vue)

**Comment by posva** [comment]
It gives you an error. Please read the issue template
