### ISSUE TITLE
<script setup> build打包 页面空白

### ISSUE THREAD

**Issue by youyawu** [vuejs/rfcs#286]
我遇到一个问题 做vue3.0开发时 开发环境页面正常显示 但build打包后 页面是空白 
找到两处有同样疑问的链接：
https://github.com/vuejs/rfcs/issues/274
https://github.com/vuejs/vue-cli/issues/6282
 但都没有给出答案
我提供了一个可测试 demo 地址为
https://github.com/youyawu/vue_demo1
希望可以得到解答

**Comment by zizyzhang** [comment]
请问这个issue为什么关闭了，是找到解决方法了吗

**Comment by suyingtao** [comment]
> 请问这个issue为什么关闭了，是找到解决方法了吗

安装最新版 vue-loader 可以解决。
https://github.com/vuejs/vue-loader/issues/1838
