### ISSUE TITLE
The CSS VAR is invalid after  npm run build

### ISSUE THREAD

**Issue by zhousg** [vuejs/rfcs#287]
`<style scoped lang='less' vars={bg,width,height}>
.xtx-skeleton {
  display: inline-block;
  position: relative;
  width: var(--width);
  height: var(--height);
  overflow: hidden;
  vertical-align: middle;`

npm run serve
![image](https://user-images.githubusercontent.com/15833290/111729570-506bec00-88aa-11eb-8315-aa6c2d5ef939.png)

npm run build
![image](https://user-images.githubusercontent.com/15833290/111729610-64afe900-88aa-11eb-8f66-a09691dbc51e.png)

问题：变量名有作用域标识，但是使用的时候却没有
Problem: the variable name has a scope identifier, but it is not used

**Comment by posva** [comment]
Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
