### ISSUE TITLE
Setup sugar cannot pass the ref to the ref function param.But I can get the ref object correctly with no sugar

### ISSUE THREAD

**Issue by cq360767996** [vuejs/rfcs#297]
When I use ref function in the parent component and ref string in the children, setup sugar cannot get the refs correctly.Here is my code, or you can view my [repo](https://github.com/cq360767996/setup-demo).

**App.vue**
```
<template>
  <HelloWorld :ref="setRef" />
</template>
<script lang="ts">
export default {
  setup() {
    const setRef = el => {
      // el is an empty object
      console.log(el); 
    };
    return { setRef };
  }
};
</script>
```

**HelloWorld.vue**
```
<template>
  <div ref="dom">demo</div>
</template>

<script lang="ts" setup>
const dom = ref();
</script>
```

**Comment by cq360767996** [comment]
When I use ref function in the parent component and ref string in the children, setup sugar cannot get the refs correctly.Here is my code, or you can view my [repo](https://github.com/cq360767996/setup-demo).

**App.vue**
```
<template>
  <HelloWorld :ref="setRef" />
</template>
<script lang="ts">
export default {
  setup() {
    const setRef = el => {
      // el is an empty object
      console.log(el); 
    };
    return { setRef };
  }
};
</script>
```

**HelloWorld.vue**
```
<template>
  <div ref="dom">demo</div>
</template>

<script lang="ts" setup>
const dom = ref();
</script>
```

**Comment by lmiller1990** [comment]
I think you just need to do

```
onMounted(() => {
  console.log(dom)
})
```

In the second one, and you will have your ref? Isn't this just a race condition, where the ref is not initialized until the component is rendered? The first example you call the function, which is only called when the DOM element exists. In the second one, this is not the case. I don't think the two snippets are equivalent.

See this example: https://v3.vuejs.org/guide/composition-api-template-refs.html#template-refs

**Comment by cq360767996** [comment]
HelloWorld.vue is the children component of the App.vue. When I use ref sugar in the Helloworld.vue, I cannot get the ref object in the setRef's first param. It's an empty object. But with no sugar in the Helloworld.vue, I can get the ref object correctly in the  setRef's first param.

**Comment by cq360767996** [comment]
HelloWorld.vue is the children component of the App.vue. When I use ref sugar in the Helloworld.vue, I cannot get the ref object in the setRef's first param. It's an empty object. But with no sugar in the Helloworld.vue, I can get the ref object correctly in the setRef's first param.

**Comment by cq360767996** [comment]
it works
```
<script lang="ts">
import { ref, onMounted } from 'vue';
export default {
  setup() {
    const dom = ref();
    return { dom };
  },
};
</script>
```

it does not work
```
<script lang="ts" setup>
import { ref } from 'vue';
const dom = ref();
</script>
```

**Comment by lmiller1990** [comment]
Did my suggestion work?

**Comment by cq360767996** [comment]
I've tried. It doesn't work.

**Comment by lmiller1990** [comment]
I just tried and it works fine for me:

```
<template>
  <img ref="theRef" alt="Vue logo" src="./assets/logo.png" />
  <HelloWorld msg="Hello Vue 3 + Vite" />
</template>

<script setup>
import { onMounted, ref } from 'vue'

const theRef = ref(null)

onMounted(() => {
  console.log(theRef.value)
})

import HelloWorld from './components/HelloWorld.vue'
</script>
```

![image](https://user-images.githubusercontent.com/19196536/113975407-ce585d00-9882-11eb-8a71-744dde0a4039.png)

**Comment by cq360767996** [comment]
I think you mistake my problem. I'd like to get the children ref in the parent component using ref function. Then the dom object will pass to the first param of this function `setRef `. While I use sugar in the children component and set the root element `ref="dom"`, I cannot get the fisrt param correctly in the context `setRef`. 
```
const setRef = el => {
  // el is an empty object
  console.log(el); 
};
```

**Comment by posva** [comment]
Don't duplicate issues, thanks.

**Comment by Abunuo** [comment]
> Don't duplicate issues, thanks.

So, what's the solution? I didn't find the original problem.

**Comment by Abunuo** [comment]
> I think you mistake my problem. I'd like to get the children ref in the parent component using ref function. Then the dom object will pass to the first param of this function `setRef `. While I use sugar in the children component and set the root element `ref="dom"`, I cannot get the fisrt param correctly in the context `setRef`.
> 
> ```
> const setRef = el => {
>   // el is an empty object
>   console.log(el); 
> };
> ```

How did you finally solve it?

**Comment by YannicEl** [comment]
same problem as @lanbin

**Comment by cq360767996** [comment]
@Abunuo Give up the sugar, then you can sovle it.

**Comment by Abunuo** [comment]
> @Abunuo Give up the sugar, then you can sovle it.

Thank you. That's what I did.

**Comment by catch6** [comment]
same problem as @lanbin

**Comment by catch6** [comment]
this is really a bug ,it should not be closed

**Comment by TheParad0X** [comment]
Why is this closed? Where is the original issue if this is a duplicate? I am having the same Problem 🤔

**Comment by LinusBorg** [comment]
script setup components are closed by default, they do not expose their state to the parent on the ref instance. The components have to explicitly expose state to the outside world.

See: https://vuejs.org/api/sfc-script-setup.html#defineexpose

However, public APIs like $el are still accessible no matter what.

[See this playground](https://sfc.vuejs.org/#__DEV__eNp9U01v2zAM/SuEMCAO4Fj31AnQw4DtNgwDdvFFtelYnS0JkpykKPzfR0l2k7ZGD/4Q9fgovUe+skdjivOIbM9Kj4PphcdjpQDKH9j3+q+2fQN7i+2hYg79b2wrBpwQJb+Dl6620njohToR0LuKRRI5GG09vILCq/8j6385uE4Q74WIciBamKC1eoANnWFzl3JXPe0X/BYKByYwXiO0wVaMPVUJ6XTG0WTbtACotXI+BKkeHEC4F1VDVuvBbOFwXFAJp3ssen3KNnUnqWwAaYXKgyQOoWoEY/X1ZZPHre0DLMnLl3O4COmh1TZeGDzdGBJbJxpaDgheQyuVdB3dXjVopTqBUA2MphE+LKR3QZiFVETKRb9su3rihhRa7IiqRs1i5fm4BUHWc8341MsaHn/9hG/Yr2RSdM6cHtLXkshWka2zsCk+5eH9JpvbL/LejIuIqVIhoeSpaY4sZ8n03SBM8ey0omaMqdW8Qe30RlYxMj+sK9Z5b9yec9fWoSOeXaHtidNfYUcVxC7QDbsnqy8OLRFXLNafOTgFz2h3yQa0X3F+gH7iXa5FV3nfpZ/HqpHn4BBNCTlCY9LgoEtO0Y8ztTpVqb/fz9baFFUqdX5ojENAZNvoUXhoXqTC7zQ8DrNZVcIlb8jpmzHTf+GjY68=)
