### ISSUE TITLE
Integrated extensive documentation for single file components

### ISSUE THREAD

**Issue by gregaton** [vuejs/rfcs#30]
I would like to propose a new top-level element for single file components to hold additional component documentation.

I've seen various solutions from different Vue frameworks and most boil down to using some external file(s) to hold advance documentation and examples.

I think it's best to keep the documentation as close as possible to the code.

My suggestion would be to add a new top-level `documentation` element to single file components. Alternatively one could add a new attribute for the `template` tag to mark one as documentation.

Functional the element should probably be very similar to the `template`. The documentation would be written using HTML but could also contain live-examples of the component itself.

To that extent, it would be very useful to also offer some global helper components/tags like an `example` component that would render its contents but also display the contents as source code. Or a way to reference the documentation of other components.

The main effort however would be to extend `vue-loader` and other tools to handle the new element appropriately. 

There could be a `generate-doc` (or similar) command that would parse all .vue files and generates static documentation and/or a new run mode that would serve a dynamic docs application on a different port.

Ideally, the contents of the new element would be combined with any inline documentation (JSDoc) to generate an extensive documentation for each component.

**Comment by posva** [comment]
Thanks for your interest. This is not something that will go here as an issue. An RFC is more of a pull request with detailed information about the proposed changes.
That being said, there are already some ongoing efforts out there like https://github.com/vue-styleguidist/vue-styleguidist#readme

Custom top level elements are already supported as a way to extend the existing component content. It's used by multiple libraries like internationalization and some testing libraries as well

**Comment by gregaton** [comment]
Alright, then I misunderstood the [README](https://github.com/vuejs/rfcs#gathering-feedback-before-submitting).

Thanks for pointing out styleguidist. I will do some digging.

I wasn't aware that custom top level elements are already supported.
Then I would also consider this less of an core issue.
