### ISSUE TITLE
`<style>` should be taken into account for `no-unused-vars` check when using `<script setup>`

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/rfcs#305]
> [ESLint rules like no-unused-vars. We will need a replacement rule in eslint-plugin-vue that takes both the `<script setup>` and `<template>` expressions into account.](https://github.com/vuejs/rfcs/blob/script-setup-2/active-rfcs/0000-script-setup.md#tooling-compatiblity)

Due to [SFC State-driven CSS Variables (v-bind in <style>)](https://github.com/vuejs/rfcs/blob/style-vars-2/active-rfcs/0000-sfc-style-variables.md), `<style>` should be taken into account as well.

**Comment by ota-meshi** [comment]
Could you follow the issues in the eslint-plugin-vue repository and comment if there are any features you think you need?

https://github.com/vuejs/eslint-plugin-vue/issues/1248
