### ISSUE TITLE
script setup 的语法糖下，如何用h来render绘制Dom？

### ISSUE THREAD

**Issue by JacBian** [vuejs/rfcs#323]

**Comment by JacBian** [comment]
`export default {
  setup() {
    const root = ref(null)

    return () =>
      h('div', {
        ref: root
      })

    // with JSX
    return () => <div ref={root} />
  }
}`
常规的setup写法如上，在
`<script lang="ts" steup >`
内有暴露api实现吗？

**Comment by sxzz** [comment]
```javascript
import { h } from 'vue'
```
https://v3.vuejs.org/api/global-api.html#h

**Comment by antfu** [comment]
`<script setup>` is used for SFC. For render function, you could use plain js/ts instead of SFC.
