### ISSUE TITLE
使用语法糖<script setup lang="ts">报is declared but its value is never read.Vetur(6133)

### ISSUE THREAD

**Issue by 332862394** [vuejs/rfcs#335]
代码如下：
<script setup lang="ts">
import { reactive, toRefs } from "vue";
import userBill from "@/utils/http/api/bill/userBill";
import { loginType, loginToken } from "@/utils/http/api/model/requestModel";
import router from "@/router/index";
import { ElMessage } from "element-plus";
interface datamModel {
  loginModel: loginType;
  loginToken: loginToken;
}
const loginPar: datamModel = reactive({
  loginModel: { UserName: "", PassWord: "" },
  loginToken: { Token: "" },
});
async function loginEvent() {
  if (!loginPar.loginModel.UserName || !loginPar.loginModel.PassWord) {
    ElMessage.warning({ message: "用户名或密码不能为空", type: "warning" });
    return;
  }
  router.push("managerPage");
}
</script>

会报警告：'loginEvent' is declared but its value is never read.Vetur(6133)
'loginEvent' is defined but never used.eslint@typescript-eslint/no-unused-vars）
发现只要在语法糖里面定义了的变量和方法，不在语法糖里面引用，但在template里面引用的话，都会报警告，请问有办法去除警告吗？

**Comment by antfu** [comment]
Vetur does not support `<script setup>` yet, try Volar https://github.com/johnsoncodehk/volar#using
