### ISSUE TITLE
<script setup> How should the name be set

### ISSUE THREAD

**Issue by TuiMao233** [vuejs/rfcs#350]
### Version
3.1.4

### Reproduction link
[https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE e3sgbXNnIH19PC9oMT5cbjwvdGVtcGxhdGU XG5cbjxzY3JpcHQgc2V0dXA XG5jb25zdCBtc2cgPSAnSGVsbG8gV29ybGQhJ1xuLy8gIG5hbWUgPz9cbjwvc2NyaXB0PiJ9](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE e3sgbXNnIH19PC9oMT5cbjwvdGVtcGxhdGU XG5cbjxzY3JpcHQgc2V0dXA XG5jb25zdCBtc2cgPSAnSGVsbG8gV29ybGQhJ1xuLy8gIG5hbWUgPz9cbjwvc2NyaXB0PiJ9)

### Steps to reproduce
~~~html
<script lang="ts" setup>
// name??
</script>
~~~

### What is expected?
can set name

### What is actually happening?
Cannot set name

---
import {  useName } from 'vue'

**Comment by posva** [comment]
Don't open issues for questions in the RFC repo. Even less duplicate them (https://github.com/vuejs/vue-next/issues/4078)
