### ISSUE TITLE
<script setup lang="ts">  Please share me the link for the document of script setup for typescript

### ISSUE THREAD

**Issue by shreyas-ananth** [vuejs/rfcs#384]
Can anyone please share me the link for official document of script setup lang="ts" which we will use with vue3. 
<script setup lang="ts"> I will require the proper syntax for all the scenarios. I'm using vuero which uses bulma framework. We use typescript and vue3 for the frontend part. 

I have added an example below for which i will have to v-model the textfield value and also need to validate the textfield before i submit. 
Please provide me the official documentation to refer for many other hard scenarios.

**Comment by shreyas-ananth** [comment]
<template>
<div class="column is-12">
                  <V-Field>
                    <label> {{ t('pages.catalogue.forms.modelNo') }}</label>
                    <input
                      v-model="addCatalogueData.item_code"
                      type="text"
                      class="input"
                      placeholder=""
                      autocomplete="given-name"
                      required
                    />
                  </V-Field>
</div>
</template>

<script setup lang="ts">
const catalogue = async () => {
  await addCatalogue(
    addCatalogueData.item_name,
    addCatalogueData.item_code,
    addCatalogueData.brand,
    addCatalogueData.category,
    addCatalogueData.uom,
    addCatalogueData.hsn,
    addCatalogueData.note
  );
  notif.success('Catalogue Added Sucessfully');
  router.push({ name: 'catalogue-list' });
};
</script>

**Comment by yyx990803** [comment]
https://v3.vuejs.org/api/sfc-script-setup.html#sfc-script-setup
