### ISSUE TITLE
vue will consider supporting responsivity for some attributes api

### ISSUE THREAD

**Issue by SGAMERyu** [vuejs/rfcs#391]
Does VUE provide a function that allows certain fields in an object to be responded to while others are not

Usage Scenarios:

Sometimes some properties of the returned object are rendered only once in the template and therefore do not require reactive updates, but other properties require reactive updates

**Comment by iamandrewluca** [comment]
I think that you need `v-once` https://v3.vuejs.org/api/directives.html#v-once

**Comment by posva** [comment]
v-once is indeed an option. You also have `markRaw()` to skip reactivity in nested objects

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
