### ISSUE TITLE
How can I use `setup="props, { emit }"` to define `props`

### ISSUE THREAD

**Issue by zhenhappy** [vuejs/rfcs#392]
![CleanShot 2021-09-24 at 11 50 04](https://user-images.githubusercontent.com/9161946/134615335-5013e134-12c7-47d7-88b9-c4f46bc9820e.png)

[https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgYmFyID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPENhbXAgOmZvbz1cImJhclwiPjwvQ2FtcD5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9zZmMudnVlanMub3JnL3Z1ZS5ydW50aW1lLmVzbS1icm93c2VyLmpzXCJcbiAgfVxufSIsIkNvbXAudnVlIjoiPHNjcmlwdCBzZXR1cD1cInByb3BzLCB7IGVtaXQgfVwiPlxuY29uc29sZS5sb2cocHJvcHMpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2Pnt7IHByb3BzLmZvbyB9fTwvZGl2PlxuPC90ZW1wbGF0ZT4ifQ==](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgYmFyID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPENhbXAgOmZvbz1cImJhclwiPjwvQ2FtcD5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9zZmMudnVlanMub3JnL3Z1ZS5ydW50aW1lLmVzbS1icm93c2VyLmpzXCJcbiAgfVxufSIsIkNvbXAudnVlIjoiPHNjcmlwdCBzZXR1cD1cInByb3BzLCB7IGVtaXQgfVwiPlxuY29uc29sZS5sb2cocHJvcHMpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2Pnt7IHByb3BzLmZvbyB9fTwvZGl2PlxuPC90ZW1wbGF0ZT4ifQ==)

**Comment by iamandrewluca** [comment]
https://v3.vuejs.org/api/sfc-script-setup.html#defineprops-and-defineemits

**Comment by posva** [comment]
Don't use rfcs for questions
