### ISSUE TITLE
I don't think there is a way around this - you need **some** form of compiler hint when you intend to treat destructured variables as refs, and it also needs to account for proper type inference (which the wrapper function does).

### ISSUE THREAD

**Issue by hajahmadkhan85** [vuejs/rfcs#493]
I don't think there is a way around this - you need **some** form of compiler hint when you intend to treat destructured variables as refs, and it also needs to account for proper type inference (which the wrapper function does).

_Originally posted by @yyx990803 in https://github.com/vuejs/rfcs/discussions/369#discussioncomment-1132130_

**Comment by hajahmadkhan85** [comment]
https://chat.mozilla.org/#/room/#mdn:mozilla.org

**Comment by posva** [comment]
Do not spam create issues or we will have to ban you. Thanks!
