### ISSUE TITLE
Final comment period clarification

### ISSUE THREAD

**Issue by darrenjennings** [vuejs/rfcs#5]
I am not insinuating that we should debate ad nauseam, but I noticed there wasn't a "final comment" period for the first RFC (that I was aware of). What is the process and can this be clarified in the README.md?

**Comment by posva** [comment]
Do you mean like a las comment + locking the conversation?

**Comment by yyx990803** [comment]
Yes, we should add explicit markers of the final comment period. I merged #2 because majority of the latest comments were about something that was dropped from it. We should follow the process more strictly for future RFCs.
