### ISSUE TITLE
Function-based Component API (extended discussion)

### ISSUE THREAD

**Issue by 59023g** [vuejs/rfcs#56]
Not sure how I found myself here, but I looked this doc over. Overall the design looks more functional. Which appears to enable much needed TS integration improvements (no longer necessary to no-op wrap components). I'm a big fan. Congrats.

I agree RE classes, mixins, and HOCs.

Thanks for the explanation and examples. And all your work. Peace!

**Comment by 59023g** [comment]
This doc: https://github.com/vuejs/rfcs/blob/function-apis/active-rfcs/0000-function-api.md

**Comment by yyx990803** [comment]
Thanks for the encouragement - however, please only open dedicated issues if you have substantial and specific arguments that you'd like us to respond to. Otherwise, it's ok to just reply to the main RFC thread.
