### ISSUE TITLE
Function-based component API (setup)

### ISSUE THREAD

**Issue by liximomo** [vuejs/rfcs#58]
I am really excited about the Function-based component API. I make an implementation [vue-function-api](https://github.com/liximomo/vue-function-api) which I can play with.

I got some troubles with the new `setup` options. How can we access the merged `data` or `computed` inherited from the parent by `context`? Is `context` an exact equivalent of `this` in vue2.x?

```js
const Comp = Vue.extend({
  template: `<div>{{ b }} {{ c }}</div>`,
  setup() {
    const a = value(1);
    const b = computed(() => {
      return a.value + 1;
    });
    return {
      a,
      b,
    };
  },
});

const vm = new Comp({
  setup(props, context) {
    const c = computed(() => {
      // how can I access the `b` without `this`?  `context.a`?
      return this.b + 1;
    });

    return {
      c,
    };
  },
}).$mount();
```

**Comment by yyx990803** [comment]
Per RFC, you cannot use `this` inside `setup()`. Logic inside `setup()` should not rely on 2.x inheritance - instead, logic of the base component should be extracted into a separately exported function:

``` js
// compA
export function useLogicA() { ... }

export default {
  setup: useLogicA
}
```

``` js
// compB
import { useLogicA } from './compA'

export default {
  setup() {
    const { a, b } = useCompA()
    // B's own logic...
  }
}
```

**Comment by liximomo** [comment]
@yyx990803 Thanks for your reply!
