### ISSUE TITLE
Function-based Component API (model usage)

### ISSUE THREAD

**Issue by backbone87** [vuejs/rfcs#59]
i am sorry i had to open this issue, but my question in the main RFC kept getting lost.

i have a question about how one would implement models or "two-way data flow" with the functional API:
```js
function useCounter(initialCount) {
  const count = value(initialCount);
  function inc() {
    count.value++;
  };

  return { count, inc };
}

export default {
  setup(props, { emit }) {
    const { count, inc } = useCounter(props.count);
    watch(count, (nextCount) => emit('update', nextCount));

    return { count, inc };
  },
}
```

is this dont the intended way?

i had some discussion with @jonaskuske in the main thread, i will just quote that here, so more reference about open questions is available:

@backbone87
> i dont think my example or your revision ~~is~~ *isnt* fully right on this, since it kinda breaks one way data flow? i mean the counter.count gets changed first then it gets emitted up, insteadof being emitted first and as a results the new value gets propagated down again. remember the setup method will not be called on updates.

@jonaskuske 
> Well, the important question here is: what do you want to achieve with the emit('update') in the first place?
> The way I imagined your example to work is like this:
The component has a counter somewhere, which is why you use useCounter in its setup. The counter is controlled from within the component, the inc method is called from the template and the component re-renders to show the updated counter – that's your unidirectional data flow.
But to allow for flexible side effects, the component also emits an update after the counter changed. This allows the parent component to listen for changes and perform side effects, e.g. logging – but you're right, those must be isolated side effects and not affect the state, or the unidirectional data flow is broken.

**Comment by LinusBorg** [comment]
First off, you have a name conflict between a prop and data returned by `setup - both are called `count`. Fixed here just to avoid confusion later.

```js
export default {
  setup(props, { emit }) {
    const { count: countInternal, inc } = useCounter(props.count);
    watch(count, (nextCount) => emit('update', nextCount));

    return { countInternal, inc };
  },
}
```

I think if you treat the count as an internal variable instead of exposing it to the component, the "One-way-data-flow" (data down, events up) works quite nicely:

```js
function useCounter(initialCount) {
  const count = value(initialCount);
  function inc() {
    count.value++;
  };

  return { count, inc };
}

export default {
  setup(props, { emit }) {
    const { inc } = useCounter(props.count);
    watch(count, (nextCount) => emit('update', nextCount));

    return { inc };
  },
}
```

In the template, you would simply use the prop - that's the original data that was passed down.

And to send an update up, you would have a method that emits the update.

And thinking about it this way makes the whole `useCounter` function a bit superfluous:

```js
export default {
  setup(props, { emit }) {
    const inc = () => emit('update', props.count + 1)
    return { inc };
  },
}
```

But if we imagine that `count` would be some heavy logic that we wanted to be extracted, then it could be a pure function that we call in the inc method:

```js
function count(value) {
  // there's no need to use any part of the new API here!
  // we could have extracted this logic out of a objects-based component's method
  // just as well. 
  return value++
}

export default {
  setup(props, { emit }) {
    const inc = () => emit('upate', count(props.count))
    return { inc };
  },
}
```

Or am I missing something?

**Comment by LinusBorg** [comment]
Okay, I think I miss something. So a question: Is this more about one of those situations where we 

* have a "copy" of a prop's value as local state and 
* then mutate this cached value,
* then sending the update to the parent?

I'm not entirely sure what the *intended* data flow or workflow is...

**Comment by backbone87** [comment]
> Or am I missing something?

idk, really. i mean the example is too simple to argue against your alternatives. but lets imagine a `useX` that needs multiple values from props (that are maybe even passed to other `useY`) and probably multiple values to emit.

i think the first question should be: do we should use `watch` to emit value changes? or is this more like a very corner use case?

**Comment by LinusBorg** [comment]
> let's imagine a useX that needs multiple values from props (that are maybe even passed to other useY) and probably multiple values to emit.

I'm sorry but this is so unspecific that I can't really come up with a pseudo example to address it. 

I understand the "gut feeling" you seem to have about an unclarity here, though.

Maybe we can come up with something more concrete written in the current API as a starting point?

**Comment by posva** [comment]
I would personally use a computed setter to trigger the side effects (the `$emit`) and save the value locally in that `countInternal` because that way you can manipulate the computed property as a local value and forget about it

**Comment by LinusBorg** [comment]
I'll close this as it seems to go nowhere
