### ISSUE TITLE
Replace `reactive` with `scope` proposal to Functional-based Component API

### ISSUE THREAD

**Issue by ycmjason** [vuejs/rfcs#67]
> Having a bad insomnia right now, so what I am going to write in this proposal might or might not make sense. Please be gentle. Just throwing ideas to try make things better for everyone.

This is a proposal for replacing `reactive` with `scope` in RFC #42 and #63.

## Motivation
This proposal aims to address the issue with `.value` in value wrapper (bindings) returned from `binding()` and `computed()`.

`.value` is the only thing from the original RFC which I am worried about. As much as I don't like `.value`, there isn't any other way to provide reactivity for primitive values without wrapping them in objects.

The existence of bindings is to compensate the fact that values are no longer required to attach to any object (previously in 2.x, values are attached to `this`), which result in not being able to provide reactivity without wrapping the value with an object.

This proposal introduces `scope()` which act as a place where value bindings could attach to. The scope object is a proxy that will forward get/set to value bindings. 

## `scope()`

```js
setup() {
  const counter = scope({
    count: binding(0),
    message: 'hello world', // short hand for binding('hello world')
    plusOne: computed(() => counter.count + 1),
    setCount: n => counter.count = n;
  });

  // do not recommend use of loose bindings/methods
  const plusTwo = computed(() => counter.count + 2);
  const plusTwoMessage = computed(() => `${plusTwo.value} is +2.`);
  const acc = () => counter.count++;

  const awesome = useAwesome(counter.count);

  return {
    ...toBindings(counter),
    ...toBindings(awesome),
    plusTwo,
    plusTwoMessage
    acc
  }
}
```

## Spreading scopes
As suggested in #63 , `scope` uses `toBindings` before spreading.

## `scope()` vs `reactive()`

While they are very similar, conceptually they are different. `reactive()` creates a reactive object whereas `scope()` provides a namespace for bindings and methods.

A reactive object implies that entries are "properties" of the object. For example, `user = reactive({ ... })` suggests that all keys in `user` is *user's* (`user.name`, `user.gender`, `user.age`...). 

Scope, on the other hand, implies that entries are just part of the namespace. For example, `user = scope({...})` suggests that `user` is just a scope. Variables attached to it do not necessarily belong to the actual "user". (`user.authenticated`, `user.errorMessage`, `user.login()`...)

## Suggest returning scopes from composition functions

It was previously mentioned by Evan https://github.com/vuejs/rfcs/issues/63#issuecomment-505804225:

> * only recommend using `reactive` directly inside `setup()`
> * when you are extracting logic into a composition function:
>   
>   * always name the function as `useXXX`
>   * always return a binding, or an object of bindings.

With the introduction to scope, I would suggest all bindings to be scoped.

So:
* avoid use of `binding()`/`computed()` outside of `scope()`
* when you are extracting logic into a composition function:
  * always name the function as `useXXX`
  * always return a scope

## Benefits
- If `binding()` and `computed()` are scoped, then no need for `.value`.
- Encourage grouping relevant things inside the same scope.

## Drawbacks
- Needing to do `namespace.prop` in exchange for getting rid of `prop.value`. (but it is probably more intuitive to do `namespace.prop` than `prop.value`.
- Loose bindings will still need to do `prop.value`. (So, `.value` is not actually solved in this proposal.)

### Could we make `setup` to return scope directly?

`setup()` returns an object with bindings and methods. This is basically a scope. So could we return scope directly which can avoid the need to `toBindings()`? A `mergeScopes` helper can be useful too.

```js
setup() {
  const counter = scope({
    count: binding(0),
    message: 'hello world', // short hand for binding('hello world')
    plusOne: computed(() => counter.count + 1),
    setCount: n => counter.count = n;
  });

  // do not recommend use of loose bindings/methods
  const plusTwo = computed(() => counter.count + 2);
  const plusTwoMessage = computed(() => `${plusTwo.value} is +2.`);
  const acc = () => counter.count++;

  const awesome = useAwesome(counter.count);

  return mergeScopes(
    counter,
    awesome,
    scope({
      plusTwo,
      plusTwoMessage
      acc
    }),
  )
}
```

### How would we mark properties as readonly?

There is a proposal of `readonly(binding)` in the original proposal (see https://github.com/vuejs/rfcs/pull/42#issuecomment-505797152). How should this be achieved with scope?

**`markReadonly`?**

```js
function useMouse() {
  const mouse = scope({
    x: 0,
    y: 0,
  });
  const update = e => {
    mouse.x = e.pageX
    mouse.y = e.pageY
  }
  onMounted(() => {
    window.addEventListener('mousemove', update)
  })
  onUnmounted(() => {
    window.removeEventListener('mousemove', update)
  })
  return markReadonly(mouse, ['x', 'y']);
}
```

**make the whole scope readonly?**

```js
function useMouse() {
  const mouse = scope({
    x: 0,
    y: 0,
  });
  const update = e => {
    mouse.x = e.pageX
    mouse.y = e.pageY
  }
  onMounted(() => {
    window.addEventListener('mousemove', update)
  })
  onUnmounted(() => {
    window.removeEventListener('mousemove', update)
  })
  return readonly(mouse);
}
```

With `mergeScopes()` which merges scopes into one. Then we can do something like `mergeScopes(readonly(doNotMutateMeScope), mutateMeScope)`.

### Funky Scope

```js
setup() {
  const counterScope = scope(counter => ({
    count: binding(0),
    message: 'hello world', // short hand for binding('hello world')
    plusOne: computed(() => counter.count + 1),
    setCount: n => counter.count = n;
  }));

  // this discourage use of `counterScope` outside
  const setCount = n => counterScope.count.value = n;

  const awesomeScope = useAwesome(counterScope.count.value);

  return {
    ...counterScope,
    ...awesomeScope,
  }
}
```

**Benefits**
- no need `toBindings()` for spreading as `counterScope` will be object of bindings.
- encourage counter things to be scoped inside `counterScope`.

**Drawbacks**
- It's hard to type `scope` (?)
- Maybe confusing that it is required to do `.value` when using `counterScope`. (But this encourage relevant things to be nested under same scope.)

**Comment by posva** [comment]
You addressed this in the alternatives with _Funky Scope_, but wouldn't

```js
const counter = scope({
    count: binding(0),
    logCount: watch(() => console.log(counter.count))
  });
```

fail because the watcher would trigger before `scope` is executed and `counter` would be `undefined`?

**Comment by ycmjason** [comment]
@posva 

not sure if `watch` belongs to scope. But if it's computed, it should work as it is not computed until accessed.

**Comment by ycmjason** [comment]
Added this to issue:

## Unresolved Issue

### How would we mark properties as readonly?

There is a proposal of `readonly(binding)` in the original proposal (see https://github.com/vuejs/rfcs/pull/42#issuecomment-505797152). How should this be achieved with scope?

**Possible Way 1**

```js
function useMouse() {
  const mouse = scope({
    x: 0,
    y: 0,
  });
  const update = e => {
    mouse.x = e.pageX
    mouse.y = e.pageY
  }
  onMounted(() => {
    window.addEventListener('mousemove', update)
  })
  onUnmounted(() => {
    window.removeEventListener('mousemove', update)
  })
  return markReadonly(mouse, ['x', 'y']);
}
```

**Comment by yyx990803** [comment]
Per RFC, `reactive` [already has the behavior you are suggesting](https://github.com/vuejs/rfcs/blob/function-apis/active-rfcs/0000-function-api.md#value-unwrapping), so this proposal boils down to just renaming `reactive` to `scope` - which I don't really think is a good idea, as it's less descriptive about what it is doing.

**Comment by ycmjason** [comment]
@yyx990803 

Thank you for your reply. I think many people has missed the fact that `reactive` can actually have `computed` and `binding` in it. That's great news!
