### ISSUE TITLE
Proposal to unify reactive and binding with simplified access to reactive data

### ISSUE THREAD

**Issue by CyberAP** [vuejs/rfcs#68]
This a proposal for a Functional API RFC #42 and for an amendment #63.

## Motivation

Amendment #63 proposes two methods to define and work with reactive data:

* `reactive` — for Vue 2.x-like reactivity, where only objects can be used as a data type
* `binding` — a method where you can use primitives as reactive values

These methods work differently and produce different APIs.
For example: `reactive` will give you direct access to the values in data.

```js
const state = reactive({ counter: 0 });

console.log(state.counter); // 0
```

At the same time, `binding` wraps values in an internal object structure, that lets you access reactive data only with on a special property called `value`.

```js
const counter = binding(0);

console.log(counter.value); // 0
```

This imposes several problems:

- Two new ways to do the same thing (we already have `data` property on the component instance)
- Confusion on when to use which
- Need for extra helpers to support spreading in objects
- A burden of using `.value` to access reactive data in `binding`

### 1. Leave only `binding` and rename it to `reactive`, make it polymorphic

Bindings should be the common reactive data structure when working with reactivity.
Since `reactive` is a more self-explanatory word in terms of what it does it fits better as the name of this functionality. `reactive` should always produce bindings, even nested bindings:

```js
const state = reactive({ foo: { bar: 0 } });

function setBar(value) {
  state.foo.bar.value = value;
}
```
```js
const counter = reactive(0);

function setCounter(value) {
  counter.value = value;
}
```
This solves the problem with having too many ways to do the same thing and also unifies the way we work with reactive values. You won't have to decide on whether to pick `binding` or `reactive` when decomposing your functions.

There is no need in `toBindings` helper as well, since we're always returning reactive objects, even if we destructure them.

```js
function useNested() {
  const state = reactive({ nested: { a: 1, b: 2 } });
  return { ...state.nested }; // a & b are bindings
}
```

### 2. Provide an easy access to reactive data with `valueOf`

Instead of constantly using `.value` every time we want to get reactive value we could make use of `valueOf` property, that would always return reactive value.

```js
const state = reactive({ foo: { bar: 0 } });

console.log(state.foo.bar); // 0
```
```js
const counter = reactive(0);

console.log(counter); // 0
```

This solves the issue with a need for `.value` to get data.

But it also has some disadvantages:

- You still have to use `.value` to set data;
- Inconsistency between reading and writing.

In general it's more common to read data than write it, so I think it's an acceptable quirk.

You can always opt-out of this functionality, since `.value` is always there.
### `setValue` helper

A `setValue` helper could be used to set reactive data, similarly to Vue 2.x `vm.$set`. That would hide the internal implementation of reactivity from us, but at the same time would be very similar to using `.value` in terms of ergonomics.

```js
const counter = reactive(0);

sertValue(counter, 0);
```

### Set primitives with `.value` and object props directly

```js
const state = reactive({ counter: 0 });

state.counter = 1;
```
```js
const counter = reactive(0);

counter.value = 0;
```

That looks very confusing and I wouldn't really consider it.

**Comment by Arxcis** [comment]
An advantage of this proposal is that it is more consistent, which leads to fewer concepts to learn:

- Everything is accessed via `.value`
```js
const counter = reactive(0)
const user = reactive({ name: 'Jonas' })

counter.value // 0
counter // ValueWrapper
user.name.value // 'Jonas'
user.name // ValueWrapper
````
- Everything may be spread in the return of `setup()` without loosing reactivity
```js
return {
    ...user, // name still reactive
    counter, 
}
```

One drawback I can think of is if you want to copy all values from a reactive object:

- Before you could do 
```js
const userCopy = {
    ...user
}
```

- Now you have to do:
```js
const userCopy = {
    firstName: user.firstName.value,
    lastName: user.lastName.value,
    email: user.email.value,
    phone: user.phone.value,
}
```
- This could be mitigated with `toValues()` (opposite of `toBindings()` proposed in #63)
```js
const userCopy = { ...toValues(user) }
```
- Alternative names
```js
const userCopy = { ...values(user) }
const userCopy = { ...value(user) }
const userCopy = { ...getValues(user) }
```

**Comment by smolinari** [comment]
I'm for proposal 2 and sort of for `setValue()`, (which btw, has a typo above).

Scott

**Comment by yyx990803** [comment]
This won't work since value types can be re-assigned. What if you start with `reactive(0)` and then set its value to an object?

I've [already said in another thread](https://github.com/vuejs/rfcs/issues/63#issuecomment-506337911) - the inherent concept of a binding is inevitable. Trying to hide it under an overloaded single API method **does not make the inherent concept go away**. Instead, it only creates confusion.

**Comment by smolinari** [comment]
Yeah. I thought I got an answer from my question. I knew I had asked it. I just couldn't find it. Sorry bout that.

Scott

**Comment by Arxcis** [comment]
> This won't work since value types can be re-assigned. What if you start with `reactive(0)` and then set its value to an object? The same variable would behave completely differently based on mutation over time. This is extremely confusing. It also completely breaks type inference.

 Makes total sense. Thank you for clarifying 👍

**Comment by CyberAP** [comment]
> This won't work since value types can be re-assigned. What if you start with `reactive(0)` and then set its value to an object? The same variable would behave completely differently based on mutation over time. This is extremely confusing. It also completely breaks type inference.
> 
> I've [already said in another thread](https://github.com/vuejs/rfcs/issues/63#issuecomment-506337911) - the inherent concept of a binding is inevitable. Trying to hide it under an overloaded single API method **does not make the inherent concept go away**. Instead, it only creates confusion.

But wouldn't that also apply to the current binding proposal? If you change a value type of a binding you get the same problem or this is limited internally and you just get an error instead?

**Comment by yyx990803** [comment]
@CyberAP a binding is always a binding, so you always access its internal value via `.value`. With your proposal you sometimes need `.value` and sometimes don't.

**Comment by CyberAP** [comment]
> @CyberAP a binding is always a binding, so you always access its internal value via `.value`. With your proposal you sometimes need `.value` and sometimes don't.

 Could you please clarify when we have to use `.value` apart from writing a value? I thought it was pretty clear that we always use `.value` for writing and direct property access for reading.

**Comment by yyx990803** [comment]
@CyberAP I was referring to your proposal (1) polymorphic `reactive`.

For (2) using `valueOf` - consider this:

``` js
const n = reactive(0)

n.value = { foo: 1 }

// there is no way to expose `n` as { foo: 1 } because `valueOf` only works on primitive value operations
```

**Comment by CyberAP** [comment]
@yyx990803 thank you for explaining this. I actually thought this could be handled internally. For primitive bindings we provide a `valueOf` method and for objects we remove that property if it has been a primitive earlier or add that property if we set an object value to a primitive. Is that not feasible?
This has a downside of using `.value` to set value even when we could just set the object property directly, but it's better for consistency overall I think.

In case of `value: 1` it should print a warning, since it's a reserved word in this approach.

Yes that sounds like a lot of quirks on the backend but for end user I think it's actually simpler than remembering two types of reactive data structures.
