### ISSUE TITLE
Suggestion for Vue 3.0 : Add the method "valueOf", "toString", "Symbol.toPrimitive" to the "ref" type

### ISSUE THREAD

**Issue by masx200** [vuejs/rfcs#85]
Suggestion for Vue 3.0 : Add the method "valueOf", "toString", "Symbol.toPrimitive" to the "ref" type
For implicit type conversion to work properly.
```js
const num=ref(8)
const xxx=ref(4)
const yyy=ref("hello")

num+xxx
//expected  : 12
//[object Object][object Object]
//
num*xxx
//expected  : 32
//NaN
yyy+xxx
//expected  : "8hello"
//[object Object][object Object]
```

**Comment by michaeldrotar** [comment]
Why would you want implicit conversion? This seems like it'd make code harder to reason about and would create more inconsistencies as other places would still need to use `.value`

Personally I was resistant to `ref` but I read this article the other day that helped me appreciate it more and the `.value` usage makes it explicit that this is a bound variable and not just a local one.
https://dev.to/ycmjason/thought-on-vue-3-composition-api-reactive-considered-harmful-j8c

**Comment by masx200** [comment]
> Why would you want implicit conversion? This seems like it'd make code harder to reason about and would create more inconsistencies as other places would still need to use `.value`
> 
> Personally I was resistant to `ref` but I read this article the other day that helped me appreciate it more and the `.value` usage makes it explicit that this is a bound variable and not just a local one.
> https://dev.to/ycmjason/thought-on-vue-3-composition-api-reactive-considered-harmful-j8c

```js
computed(()=>{ 

return ref(6)*ref(7)

})

```

**Comment by michaeldrotar** [comment]
> ```js
> computed(()=>{ 
> 
> return ref(6)*ref(7)
> 
> })
> ```

There's no reason to use `ref` here... probably a case of an overly-simplified example since you'd obviously just use `42`.. but aside from that, you can just use `computed(() => 6 * 7)`

I think `value` still reads better in a fuller example
```js
const foo = ref(6);
// ... do some work...

const bar = ref(7);
// ... do some work...

const baz = computed(() => foo.value * bar.value);

return { foo, bar, baz };
```

**Comment by yyx990803** [comment]
I think this is a bad idea. It's implicit and magical, and only works in a limited number of edge cases, and doesn't play well with types.

**Comment by masx200** [comment]
> I think this is a bad idea. It's implicit and magical, and only works in a limited number of edge cases, and doesn't play well with types.

Novice friends may often forget to write ".value"

**Comment by masx200** [comment]
> I think this is a bad idea. It's implicit and magical, and only works in a limited number of edge cases, and doesn't play well with types.

Can issue a warning when auto-implicit conversion

**Comment by michaeldrotar** [comment]
It can also actively hurt things since its implicit.

The composition api is also targeted for advanced users.. people starting out are probably better suited to learn the classic api first.

I'm sure this seems like an easy and free thing with no downsides but implicit stuff can be a source of the worst types of bugs and can be a huge pain point.

**Comment by masx200** [comment]
It is recommended to use the "eslint" plugin to enforce the requirement. For "ref" objects and "reactive" objects, you must use the "const" declaration.

**Comment by hsxfjames** [comment]
I think it could warn for implicit use under dev mode like:
```js
if (__DEV__) {
  r.toString = () => {
    console.warn('implicit toString() is not valid')
  }
  ....
}
```

**Comment by comfuture** [comment]
Agree. I think it is quite natural that ref<T> has the value of T and corresponds to the operator of T.
Many dynamic languages provide a similar feature, and no one considers it to be inconsistent.
It doesn't make sense to think that `.value` is good and `.valueOf` is bad.
