### ISSUE TITLE
 to abolish the "with(){}" syntax in the template compiler in "vue3.0" to improve performance.

### ISSUE THREAD

**Issue by masx200** [vuejs/rfcs#91]
The "with" syntax has been banned in strict mode and performance is not very good.

 to abolish the "with(){}" syntax in the template compiler in "vue3.0" to improve performance.

https://github.com/vuejs/vue-next/blob/ed29af7bea4f4f78f50992213b56e41bb5bc9052/packages/compiler-core/__tests__/transforms/__snapshots__/hoistStatic.spec.ts.snap

https://github.com/vuejs/vue-next/blob/e98a85f3cbda7e2c34955295f0a353d42bd48f8c/packages/compiler-dom/__tests__/transforms/__snapshots__/vModel.spec.ts.snap

https://github.com/vuejs/vue-next/blob/1c0a2c6d41dc09706b8c932440d8d519ceb34c57/packages/compiler-core/__tests__/__snapshots__/codegen.spec.ts.snap

```js
return function render() {
  with (this) {
    return _createVNode(\\"div\\", {
      id: \\"foo\\",
      [prop]: bar,
      [foo + bar]: bar
    }, [
      _createVNode(\\"p\\", { \\"some-key\\": \\"foo\\" })
    ], 16)
  }
}
```

**Comment by yyx990803** [comment]
Function mode / `with(){}` is only used when you are using the in-browser compiler. Stripping `with` requires proper JavaScript AST analysis, so it depends on a full JavaScript parser, which will be too heavy for the in-browser build. This is a necessary trade off. In practice, in-browser builds are also not typically perf sensitive and the cost of `with` is acceptable.

Pre-compiled templates will be in module mode (strict by default) and will not be using `with` anyway.
